### ISSUE TITLE
docker build failed due to gradle oneJar in job-dsl-plugin

### ISSUE THREAD

**Issue by arulrajnet** [visualphoenix/jenkins-xml-to-jobdsl#46]
The error log while running command

```
docker build -t jdsl .
```
Log

```
Download https://plugins.gradle.org/m2/org/jenkins-ci/annotation-indexer/1.4/annotation-indexer-1.4.jar

FAILURE: Build failed with an exception.

* Where:
Build file '/jdsl/job-dsl-plugin/build.gradle' line: 14

* What went wrong:
An exception occurred applying plugin request [id: 'org.jenkins-ci.jpi', version: '0.38.0']
> Failed to apply plugin [id 'org.jenkins-ci.jpi']
   > Could not find method register() for arguments [server, class org.jenkinsci.gradle.plugins.jpi.ServerTask, org.jenkinsci.gradle.plugins.jpi.JpiPlugin$_apply_closure1@697889b6] on task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 34s
The command '/bin/sh -c true  && git clone https://github.com/jenkinsci/job-dsl-plugin.git /jdsl  && cd /jdsl  && gradle oneJar' returned a non-zero code: 1
```
Seems job-dsl-plugin moves to gradle 5.6.4 version.

**Comment by Matt812g** [comment]
This is still happening.

**Comment by Matt812g** [comment]
> [ 8/13] RUN true  && git clone https://github.com/jenkinsci/job-dsl-plugin.git /jdsl  && cd /jdsl  && gradle oneJar:                                                 
0.191 Cloning into '/jdsl'...                                                                                                                                           
5.095 Starting a Gradle Daemon (subsequent builds will be faster)                                                                                                       
8.895                                                                                                                                                                   
8.896 FAILURE: Build failed with an exception.                                                                                                                          
8.899 
8.899 * What went wrong:
8.901 Task 'oneJar' not found in root project 'jdsl'.
8.902 
8.902 * Try:
8.995 Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
9.008 
9.009 * Get more help at https://help.gradle.org
9.011 
9.011 BUILD FAILED in 4s
------
Dockerfile:46
--------------------
  45 |     
  46 | >>> RUN true \
  47 | >>>  && git clone https://github.com/jenkinsci/job-dsl-plugin.git /jdsl \
  48 | >>>  && cd /jdsl \
  49 | >>>  && gradle oneJar
  50 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c true  && git clone https://github.com/jenkinsci/job-dsl-plugin.git /jdsl  && cd /jdsl  && gradle oneJar" did not complete successfully: exit code: 1
